# Grafana Security Configuration
# Auto-generated by Vault Agent - DO NOT EDIT MANUALLY
# Last updated: {{ timestamp }}

[security]
{{ with secret "grafana/admin" }}
admin_user = {{ .Data.data.username }}
admin_password = {{ .Data.data.password }}
{{ end }}

[auth]
disable_login_form = false
disable_signout_menu = false