# JanusGraph Authentication Configuration
# Auto-generated by Vault Agent - DO NOT EDIT MANUALLY
# Last updated: {{ timestamp }}

{{ with secret "janusgraph/admin" }}
authentication.default.username={{ .Data.data.username }}
authentication.default.password={{ .Data.data.password }}
{{ end }}

# Connection settings
gremlin.remote.driver.clusterFile=conf/remote-objects.yaml
gremlin.remote.driver.sourceName=g