# OpenSearch Security Configuration
# Auto-generated by Vault Agent - DO NOT EDIT MANUALLY
# Last updated: {{ timestamp }}

{{ with secret "opensearch/admin" }}
opensearch.username: {{ .Data.data.username }}
opensearch.password: {{ .Data.data.password }}
{{ end }}

# Security settings
opensearch.ssl.enabled: false
opensearch.security.enabled: false