# Pulsar Authentication Configuration
# Auto-generated by Vault Agent - DO NOT EDIT MANUALLY
# Last updated: {{ timestamp }}

{{ with secret "pulsar/admin" }}
authenticationEnabled=true
authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderToken
tokenSecretKey={{ .Data.data.token }}
{{ end }}

# Broker settings
brokerServicePort=6650
webServicePort=8080