apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: janusgraph-banking-ci
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: main
    - name: image-registry
      type: string
      default: image-registry.openshift-image-registry.svc:5000
    - name: image-name
      type: string
      default: janusgraph-banking/api
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: test
      taskRef:
        name: run-tests
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build
      taskRef:
        name: build-image
      runAfter:
        - test
      params:
        - name: image
          value: $(params.image-registry)/$(params.image-name):$(params.git-revision)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: scan
      taskRef:
        name: trivy-scan
      runAfter:
        - build
      params:
        - name: image
          value: $(params.image-registry)/$(params.image-name):$(params.git-revision)
