apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: janusgraph-banking-push
spec:
  params:
    - name: git-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: janusgraph-banking-ci-
      spec:
        pipelineRef:
          name: janusgraph-banking-ci
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.after)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-push-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: push
      bindings:
        - ref: github-push-binding
      template:
        ref: janusgraph-banking-push
